apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ci-robot
  namespace: default
rules:
- apiGroups:
  - ""
  - "apps"
  resources:
  - deployments
  - services
  - pods
  - pods/exec
  - pods/log
  - persistentvolumeclaims
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: ci-robot-rolebinding
subjects:
- kind: ServiceAccount
  name: ci-robot
  namespace: default
roleRef:
  kind: Role
  name: ci-robot
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ci-robot
  namespace: default