hostNetwork: true
controller:
  config:
    name: nginx-ingress-config
    entries:
      client-max-body-size: "300m"
  service:
    externalIPs: ["192.168.33.10"]
    type: NodePort
    httpPort:
      nodePort: 80
    httpsPort:
      nodePort: 443